name: Publish Docker image to GitHub Container Registry and Docker Hub
on: 
  push:
      branches:
        - main

jobs:
  build_and_push:
    name: Push image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: pl-covid-stats-scraper
          tags: v1, latest
          registry: ghcr.io
          dockerfile: Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
