name: Scrape the data!
on:
  schedule:
    - cron: '*/10 * * * *'
    - cron: '31 11 * * *'

jobs:
  scrape:
    name: Scrape that data!
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: |
        docker run --rm -e CONNECTION_URL="${{ secrets.CONNECTION_URL }}" ghcr.io/koralowiec/pl-covid-stats-scraper:latest
